#!/bin/zsh

mkdir "$1.wip"
cp templates/nnn_test "$1.wip/$1_test.go"
cat templates/nnn1 | sed "s/nnn/$1/g" >  "$1.wip/$1.go"
templates/description "$1"            >> "$1.wip/$1.go"
cat templates/nnn2 | sed "s/nnn/$1/g" >> "$1.wip/$1.go"
